### ----------------------------------------
### COLECCIÓN 1: MUSIC
### ----------------------------------------


GET http://localhost:3000/music

### GET team by ID

GET http://localhost:3000/music/6a6a87dc965afb9bfde5a12e

### CREATE team

POST http://localhost:3000/music HTTP/1.1
content-type:application/json

{
  "_id": "6a6a87dc965afb9bfde5a12e",
  "album_name": "After Hours",
  "artist": "The Weeknd",
  "duration_seconds": 200,
  "genre": "Synthpop",
  "release_year": 2019,
  "title": "Blinding Lights"
}

### UPDATE team

PUT http://localhost:3000/music/6a6a87dc965afb9bfde5a12e HTTP/1.1
content-type:application/json

{
    "album_name": "After Hours",
    "artist": "The Weeknd",
    "duration_seconds": 200,
    "genre": "Synthpop",
    "release_year": 2019,
    "title": "Blinding Lights"
}

### DELETE team

DELETE http://localhost:3000/music/6a6a87cb965afb9bfde5a12d


### ----------------------------------------
### COLECCIÓN 2: ARTISTS
### ----------------------------------------

GET http://localhost:3000/artists

### GET team by ID

GET http://localhost:3000/artists/6a6aa8c7771bde4eacb4a687

### CREATE team

POST http://localhost:3000/artists HTTP/1.1
content-type:application/json

{
  "active_since": 2004,
  "country": "United States",
  "genre": "Funk / Pop / R&B",
  "is_touring": "true",
  "name": "Bruno Mars",
  "record_label": "Atlantic Records",
  "total_albums": 3
}

### UPDATE team

PUT http://localhost:3000/artists/6a6aabfbf314df443c7a6820 HTTP/1.1
content-type:application/json

{
  "active_since": 2004,
  "country": "United States",
  "genre": "Funk / Pop / R&B",
  "is_touring": "true",
  "name": "Bruno Mars",
  "record_label": "Atlantic Records",
  "total_albums": 3
}

### DELETE team

DELETE http://localhost:3000/artists/6a6aabfbf314df443c7a6820

### ----------------------------------------
### COLECCIÓN 2: ALBUMS
### ----------------------------------------

GET http://localhost:3000/albums

### GET team by ID

GET http://localhost:3000/albums/6a6aa8c7771bde4eacb4a687

### CREATE team

POST http://localhost:3000/albums HTTP/1.1
content-type:application/json

{
    "artist_name": "Taylor Swift",
    "title": "1989 (Taylor's Version)",
    "release_year": 2023,
    "genre": "Pop",
    "total_tracks": 21,
    "is_explicit": false,
    "producer": "Jack Antonoff"
}

### UPDATE team

PUT http://localhost:3000/albums/6a6aabfbf314df443c7a6820 HTTP/1.1
content-type:application/json

{
    "artist_name": "Taylor Swift",
    "title": "1989 (Taylor's Version)",
    "release_year": 2023,
    "genre": "Pop",
    "total_tracks": 22,
    "is_explicit": false,
    "producer": "Jack Antonoff"
}

### DELETE team

DELETE http://localhost:3000/albums/6a6aabfbf314df443c7a6820

### ----------------------------------------
### COLECCIÓN 2: TOUR_DATES
### ----------------------------------------

GET http://localhost:3000/tour_date

### GET team by ID

GET http://localhost:3000/tour_date/6a6aa8c7771bde4eacb4a687

### CREATE team

POST http://localhost:3000/tour_date HTTP/1.1
content-type:application/json

{
"performer": "Taylor Swift",
    "tour_name": "The Eras Tour",
    "city": "Los Angeles",
    "country": "United States",
    "venue": "SoFi Stadium",
    "event_date": "2023-08-09",
    "is_sold_out": true
}

### UPDATE team

PUT http://localhost:3000/tour_date/6a6aabfbf314df443c7a6820 HTTP/1.1
content-type:application/json

{
"performer": "Taylor Swift",
    "tour_name": "The Eras Tour",
    "city": "Los Angeles",
    "country": "United States",
    "venue": "SoFi Stadium",
    "event_date": "2024-08-09",
    "is_sold_out": true
}

### DELETE team

DELETE http://localhost:3000/tour_date/6a6aabfbf314df443c7a6820